<?php
$title = "Luxury Premier Realty –Term and Conditions Page. ";
$description = "Luxury Premier Realty-binding agreement page. Compile all the legal information you require to buy, sell or rent with Luxury Premier Realty on thousands of listings that are updated.";
include("./include/header.php") ?>



<div class="container text-white mt-5 pt-5">
    <h2 class="juana fw-bold text-center pt-5 text-white">Term and Conditions</h2>
    <div class="d-flex justify-content-center">
        <div style="height: 2px; width: 27%; background-color: #fad393; margin-bottom: 20px;"></div>
    </div>

    <p class="mt-5 ">The accompanying Luxury Premier Realty Terms of Use ("Terms") provide significant information regarding your legal rights, obligations, and remedies regarding your access to and use of the Service, By using or accessing the Service, you consent to and agree to be bound by these Terms, our Privacy Policy (which is hereby incorporated into these Terms by reference), as well as, as applicable, our Exclusive Buyer/Renter Brokerage Agreement ("Buyer Agreement") and, as applicable, our Listing Agreement, Disclosures & Disclaimers ("Listing Agreement"), should an Owner choose to have listed their property on the MLS Service.</p>
    <p class="">You ("you" or "your") and Luxury Premier Realty (Luxury Premier Realty "") are bound by these Terms. All users or visitors to the Website and/or Service are referred to as "you" for clarity's sake throughout these Terms. The only parties to these Terms are you and Luxury Premier Realty, who may be referred to as either a "Party" or "Parties" in either the singular or plural. You must adhere to these terms in order to access and use the website and service. When you list, buy, or rent Property through the Service, as appropriate, you may also be subject to additional terms and conditions outlined in the Buyer Agreement and Listing Agreement.</p>
    <p class="">At any time, Luxury Premier Realty may, in its sole discretion, change, suspend, discontinue, impose restrictions on, or terminate any aspect of the Service with or without prior notice. Your only option, if you don’t like the alterations, is to stop using the Service altogether. You are expressing your agreement to be bound by the revised Terms by continuing to access or use the Service.</p>
    <p class="fw-bold">IF YOU DO NOT AGREE TO ALL OF THESE TERMS, YOU ARE NOT AUTHORIZED TO USE THE SERVICE.</p>
    <h4 class="fw-bold juana">DEFINITIONS</h4>
    <p class="">The following terminology shall have the following definitions for the purposes of this terminology: "Buyer" means a person who uses the Service to find and acquire a Property. "Content" refers to all information, data, text, design elements, graphics, images, audio, video, and other content present in or delivered via the Website or otherwise made available by Luxury Premier Realty in connection with the Service, with the exception of Personal Information.</p>
    <p class="">"Documentation" refers to the online instructions for using the Service that are made available to Users via the Website.</p>
    <p class="">Regardless of whether they are based on common law, a statute, rule, ordinance, agreement, contract, treaty, convention, or something else, intellectual property rights refer to all legally recognized forms of intellectual property and the rights therein. This includes the full extent to which such rights may arise or be recognized under any law, rule, or regulation, whether federal, state, local, or foreign.</p>
    <p class="">Owner" refers to a user who lists a Property for sale or rental through the Service. </p>
    <p class="">Any and all payment processing services used or offered by Luxury Premier Realty ’s third-party payment processor(s) in conjunction with your use of the Service are referred to as "Payment Services."   </p>
    <p class="">An individual's name, address, social security number, and any other information relating to an identified or identifiable individual are all considered to be personal information. Personal information also includes any information that does or can be used to contact, locate, or identify a specific individual. According to the Gramm-Leach-Bliley Act (15 U.S.C. 6801 et seq.) and the Health and Insurance Portability and Accountability Act of 1996 (42 U.S.C. 1320d), "personal information" includes "nonpublic personal information," "protected health information," and "Personal Data" as those terms are defined in the EU Data Protection Directive (Directive 95/46/EEC) and its successor, the General Data Protection Regulation </p>
    <p class="">The term "process" refers to carrying out any operation or set of operations on any data, information, material, work, expression, or other Content, such as collecting, capturing, processing, recording, receiving, inputting, uploading, downloading, recovering, reproducing, storing, organizing, combining, logging, cataloging, cross-referencing, managing, maintaining, calculating, copying, adapting, altering, translating, or creating derivative works, processing, retrieving, output, using, disseminating,</p>
    <p class="">Any residential real estate that is posted and made available for purchase or rental through the Service is referred to as "Property."</p>
    <p class="">A person who utilizes the Service to find and rent a Property is referred to as a "Renter." </p>
    <p class="">The term "technological safeguard" refers to any code, device feature, or functionality that Luxury Premier Realty has knowingly provided and that it may at any time lawfully invoke under its sole and exclusive discretion in order to monitor, detect, document, prevent, limit, deny, interrupt, or terminate unauthorized, improper, or illegal access to or use of the Website and/or the Documentation.</p>
    <p class="">"User" refers to any and all visitors to the website, including, where appropriate, Buyers, Owners, and Renters.</p>
    <p class="">User Data does not include, and expressly excludes, any code, information, Content, or data owned by us or any third-party licensor of Luxury Premier Realty, and is defined as any information or data, including, without limitation, any Personal Information, that a User at any time uploads, enters, inputs, sends, transmits, or otherwise makes available for processing through or using the Service.</p>
    <h4 class="fw-bold juana">ACCESSING THE SERVICE </h4>
    <p class="">Limited License. For the duration of the applicable term and subject to and expressly conditioned on your compliance with these Terms, including timely payment of all amounts owed, we hereby grant to you a personal, non-transferable, revocable, non-exclusive, worldwide right and license ("License") to (i) access and use the Service and the Website; and (ii) access and view the Documentation via the Website.</p>
    <p>Laws, Rules, and Regulations. You agree that you are responsible for, and will abide by, all laws, rules, and regulations applicable to your access and use of the Service, including any transactions entered into through the Service. Owners further agree that you are responsible for, and will abide by, all laws, rules, ordinances, and regulations applicable to the listing of your Property and all related conduct, including, but not limited to, those relating to taxes, credit cards, data and privacy, permits or license requirements, zoning ordinances, safety compliance and compliance with all anti-discrimination and fair housing laws, as applicable. There may be circumstances where we are legally obligated (as we may determine in our sole discretion) to share information, including Personal Information, you provide through the Service or otherwise in order to comply with requests from governmental bodies in relation to investigations, litigation, or administrative proceedings, but, unless restricted by applicable law, we will inform you of such request before sharing the information. </p>
    <p>Network Transmissions: You are aware that in order for the Website, your Content, and your User Data to be processed and sent technically, there may be a need for (i) transmissions over a variety of networks, and/or (ii) modifications to conform and adapt to the technical requirements of connecting networks or devices. </p>
    <p>By using the Service, you consent to receive emails and texts, whether from the Service or directly from Luxury Premier Realty or another User, regarding the listing, purchasing, or renting of a Property, service or customer support requests, and Luxury Premier Realty marketing materials, newsletters, or other information that may be of interest to you based on your preferences. Every email from Luxury Premier Realty contains a link to opt out of these communications.</p>
    <p>User Data: You acknowledge that you may not use any User Data about other Users that you get from or through the Service, any communication, transaction, or software associated with the Service, for any unlawful purpose or with any unlawful intent. </p>
    <p>Maps provided by Google are subject to the Google Maps terms and conditions found at: http://www.google.com/intl/en_us/help/terms_maps.html. We cannot guarantee the accuracy or quality of any User-contributed Content that is translated for display on the Website, and you are solely responsible for the review, verification, and accuracy of such translation. </p>
    <h4 class="fw-bold juana">REGISTRATION OF ACCOUNTS AND SECURITY</h4>
    <p>Each registered User will have a unique, non-transferable account and password for access to that User's Account, which may not be shared or used by more than one person. Accounts and Passwords. In order to access and use certain functionalities of the Service, the User will be required to register for a User-specific account and password ("Account").</p>
    <p>Account Security. You agree to (i) keep your password and user ID secure and strictly confidential, (ii) notify us right away and choose a new user ID and password if you believe your password for either your User Account with us or your associated email account may have become known to an unauthorized person, and (iii) upon our request, you agree to promptly change your user ID and password and take any other necessary precautions.</p>
    <p>Telephone Security. For security reasons, Luxury Premier Realty will substitute your personal telephone number with a free redirection telephone number consisting of a toll-free telephone number and an individual extension assigned to your User Account, which will send all calls to your original telephone number provided when creating your Account. </p>
    <p>You acknowledge and agree that (i) the Owner reserves the right, and (ii) you may be required, to enter into one or more separate agreements, such as a Buyer Agreement, or provide additional information, including, but not limited to, entering into a lease agreement, concluding a background check (including an independent credit and/or criminal history check), and signing waivers or terms and conditions. We do not in any way guarantee that the information you provide will be kept confidential.  </p>
    <p>Account Termination. Luxury Premier Realty, in its sole discretion, may terminate your password, Accounts (or any part thereof), and/or your right to use the Service, and, except as provided by applicable law and our Privacy Policy, remove and discard any and all of your Content and User Data, at any time for any reason or no reason, including, without limitation, for lack of use, failure to timely pay any fees or other monies due, or if we believe that you have violated or acted inconsistently with the letter or spirit of these Terms. You agree that any termination of your right to use the Service may be effected without prior notice, and acknowledge and agree that, except as provided by applicable law and our Privacy Policy, we may immediately deactivate or delete your Account and all related Content, User Data, and files related to your Account and/or bar any further access to such files or the Service. Further, you agree that Luxury Premier Realty shall not be liable to you or any third party for any termination of your right to use or otherwise access the Service or Website. </p>
    <h4 class="fw-bold juana">Own Content</h4>
    <p>You acknowledge and agree that if you submit, make available, or make any content available through the Service ("Owner Content"), you hereby grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, transferable, and multiple tiers sub-licensable right and license to use, reproduce, adapt, modify, distribute, translate, publish, create derivative works based on, perform, display, and otherwise exploit Owner Content, in whole or in part. </p>
    <p>You represent and warrant that the Owner Content (i) does not violate, misappropriate, or otherwise conflict with the rights, including intellectual property rights, of any third party, (ii) complies with all applicable laws and regulations, and (iii) must be complete, accurate, and truthful. Owner Representation and Warranty. You represent and warrant that you own or otherwise have all the rights, power, and authority necessary to grant the foregoing license.  </p>
    <p>Display of Content: Photographs should show the actual Property as the main subject of the photograph and may not include children or adults if you do not have their legal consent. Owners are responsible for reviewing and ensuring that any Content displayed on the Website appears as the Owner intended.</p>
    <p>Owner Listings: You acknowledge and agree that if you submit a listing through the Service, you represent and warrant that (i) you are the owner of the property and have all rights to list it for sale or rent, as appropriate, or that you are authorized to act on behalf of the Property Owner(s) to list the Property for sale or rent, and (ii) the listing of the Property is complete, accurate, and truthful.</p>
    <p>The following restrictions apply to your use of the Service: You accept that you are responsible for all Content and User Data, in whatever form that you supply or otherwise make available to or through the Service, including to other Users.</p>
    <ul class="lh-lg">
        <li>• uploading, posting, emailing, transmitting, or otherwise making accessible any Content or User Data that is illegal, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invading another person's privacy, hateful, or otherwise objectionable on the basis of race, ethnicity, or other factors;</li>
        <li>• upload, post, email, transmit, or otherwise make public any incorrect, inaccurate, incomplete, out-of-date, or deceptive Content or User Data;</li>
        <li>• victimize or inflict damage on youngsters;</li>
        <li>• support gambling, gaming, lotteries, raffles, competitions, sweepstakes, and/or any other activity that involves the awarding of prizes, excluding raffles, competitions, or sweepstakes that are legally compliant;</li>
        <li>• pose as someone else, including but not limited to our representative, or falsely claim or otherwise suggest that you are associated with someone else;</li>
        <li>• fabricate headers or otherwise tamper with identifiers to mask the source of any Content or User Data sent through the Service;</li>
        <li>• upload, post, email, transmit, or otherwise make available any Content or User Data that you are not authorized to make available by any law, contract, or other fiduciary relationship (such as insider information, proprietary information, and confidential information learned or disclosed through employment relationships or under nondisclosure agreements);</li>
        <li>• upload, post, email, transmit, or otherwise make public any Content or User Data that violates the intellectual property or other proprietary rights of any person or entity, including any patents, trademarks, trade secrets, copyrights, or other intellectual property;</li>
        <li>• upload, post, email, transmit, or otherwise make available any content or user data associated with the purchase, lease, rental, or provision of goods and services other than content or user data associated with the purchase, lease, rental, or provision of Properties and associated goods and services provided by Owners in conjunction with Properties;</li>
        <li>• stalk or otherwise abuse any individual or group;</li>
        <li>• gather or save personal data about other users in conjunction with the actions and behaviors that are forbidden as described in the aforementioned paragraphs.</li>
    </ul>
    <p>Certain Remedial Rights. You acknowledge and agree that Luxury Premier Realty may keep a copy of your Content and may also disclose a copy of your Content to third parties for any reason, including, without limitation, if required by law or in the good faith belief that such keeping or disclosing is necessary to: (a) comply with legal process; (b) enforce these Terms; (c) address complaints that any of your Content violates the rights of third parties; and/or (d) protect the rights, Proper</p>
    <h4 class="fw-bold juana">Telephone Content</h4>
    <p>Trademarks. The trademarks, service marks, and logos used and displayed in connection with the Service are registered and unregistered trademarks or service marks of us. Other company, product, and service names used in connection with the Service may be trademarks or service marks owned by third parties (“Third-Party Trademarks”, and, collectively with our Trademarks, the “Trademarks”). The use of the Service shall not be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark displayed in connection with the Service without the prior written consent of our specifications for each such use. The Trademarks may not be used to disparage us, any third party, or third party's products or services, or in any manner (in our sole judgment) that may damage any goodwill in the Trademarks. Use of any Trademarks as part of a link to or from any website is prohibited unless we approve the establishment of such a link by prior written consent specific for each such link.  </p>
    <h4 class="fw-bold juana">SUPPORT AND SECURITY FOR WEBSITES</h4>
    <p>Ancillary Facilities are any hardware, connectivity, third-party software, communications services, bandwidth, and other goods, software, services, and facilities required to access and use the Website or otherwise exercise the License granted under subsection 2.1 above ("Ancillary Facilities"). In no event shall Luxury Premier Realty have any obligation to provide, maintain, or support such Ancillary Facilities.</p>
    <p>Technological Safeguards. We shall have the right, but shall not be obligated, to use Technological Safeguards in a lawful manner at any time, including but not limited to (a) monitoring access to and use of the Website and the Documentation; (b) identifying, documenting, preventing, restricting, denying, interrupting, or terminating any User's or person's unauthorized or illegal access to or use of the Website or the Documentation.</p>
    <p>You acknowledge that your acceptance of these Terms, use of the Website, and exercise of the License are voluntary and undertaken with full knowledge and awareness that such activities necessarily entail risks, including security breaches, unavailability, loss, or corruption of data, and other inherent risks associated with computer software, co-operation, and the Internet.</p>
    <h4 class="fw-bold juana">ADVANCED SERVICES</h4>
    <p>The MLS Service is provided by Luxury Premier Realty pursuant to an executed Listing Agreement. The mere availability of the MLS Service is not a solicitation by us to become a listing broker. Luxury Premier Realty enables you to list your Property on an MLS Service that notifies brokers and/or real estate agents who subscribe to the MLS Service that the Property is for sale or for rent. </p>
    <p>Mortgage Payments Calculator. We provide Users with a mortgage calculator that estimates monthly mortgage payments, and other fees, based on specific criteria provided by the Owner and/or Buyer and based on the Property. The mortgage calculator is only intended to illustrate the approximations of mortgage payments associated with a Property and is neither an accurate nor complete representation of the actual mortgage payments in connection with the Property. </p>
    <p>Buyers may be given access to third-party links of real estate lawyers, title companies, surveyors, mortgage companies, trade professionals, moving companies, and other service providers. We provide these links only as a convenience to our users, and the inclusion of such third-party names or links is neither an endorsement nor a recommendation.</p>
    <p>Sample Legal Forms. Luxury Premier Realty may provide sample legal forms for your use; however, these forms are not intended to be legal advice and should not be regarded as such. They are also provided without any express or implied representations or warranties, and no representation is made as to their validity, accuracy, or completeness. Users are advised to consult a lawyer or other qualified legal professional for advice. </p>
    <p>Photography Packages. Owners can acquire professional real estate photography services from Luxury Premier Realty, which comprise 24 as-taken, high-definition pictures of the property in question. </p>
    <p class="fw-bold">LUXURY PREMIER REALTY SERVICE FEES, THE BUYER PROGRAM: BUY WITH </p>
    <h4 class="fw-bold juana">Luxury Premier Realty</h4>
    <p>The owner will pay such amounts to the Buyer's agent in the case of the purchase of the Property, at the time of closing. Buyer Service Fee. Subject to and in accordance with an executed Buyer Agreement, Luxury Premier Realty charges, as applicable, (i) Buyers a 1% flat fee with a minimum of $999 for the purchase of a Property listed on the Website or syndicated by a third party website or by a real estate brokerage company. </p>
    <p>SELL WITH Luxury Premier Realty’S SERVICE FLAT FEE. Subject to and in accordance with an executed Listing Agreement, Luxury Premier Realty charges Owner a one-time flat fee in accordance with the pricing listed on the Website for the Basic package ($99) and Enhanced Package ($399) ("Flat Fee"), for the listing of their property through the MLS Service.</p>
    <p>SELL WITH Luxury Premier Realty CONCIERGE SERVICE 1% FEE. Subject to and in accordance with an executed Listing Agreement, Luxury Premier Realty charges the Owner a one-time $599 upfront flat fee in accordance with the pricing listed on the Website and a 1% commission fee at the time of closing. Upfront Payment is due upon execution of the Listing Agreement. A 1% commission is calculated on the final closing price.</p>
    <h4 class="fw-bold juana">TERMS OF PAYMENT AND SERVICES</h4>
    <p>Payment Method. You retain sole responsibility for the accuracy and completeness of your credit card information, and you authorize our third-party payment processor(s) to store and charge your credit card as described in these Terms. We are not liable for any loss incurred by you as a result of incorrect credit card information provided by you.</p>
    <p>Updates: Luxury Premier Realty. or its third-party payment processor may, at its sole discretion and without prior notice, improve, enhance, modify, restrict, limit, or add features to its Payment Services at any time. Notification of such changes will be posted through the Service. If you disagree with the changes, your only option is to stop using the Service. </p>
    <p>If there is a conflict between these Terms and the terms and conditions that apply to a particular Payment Service, the latter terms and conditions will control with respect to your use of or access to that Payment Service.</p>
    <p>Additional Terms. You may be required to accept additional terms and conditions in order to access or use certain Payment Services.</p>
     <p>Third-party Processors. We are not responsible for any such costs and disclaim all liability in this regard. Certain third-party payment processors may charge you additional fees when processing payments in connection with the Payment Services.  </p>
     <p>Legal Compliance. You may use the Payment Services only as permitted by United States law, the laws of the jurisdiction in which you reside, and any other applicable laws. For example, but without limitation, the Payment Services may not be used to send or receive funds to: (i) any United States embargoed countries; or (ii) anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce's Deniable Persons list.</p>
</div>



<?php include("./include/footer.php") ?>